version: '3.9'
services:

  spring_container:
    container_name: spring_container
    image: demo/java_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres_container:5432/postgres
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
    depends_on:
      - postgres_container

  postgres_container:
      image: "postgres:latest"
      container_name: "postgres_container"
      environment:
        POSTGRES_DB: "postgres"
        POSTGRES_USER: "admin"
        POSTGRES_PASSWORD: "admin"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      restart: no

volumes:
  postgres_data: